config:
  path: "/conf/config.yml"
web:
  apihost: "0.0.0.0:3000"
  debughost: "0.0.0.0:4000"
  readtimeout: "5s"
  writetimeout: "5s"
  shutdowntimeout: "5s"
debug: false
db:
  filename: "wasaphoto.db"
  temp: true
