config:
  path: "/custom/config.yml"
web:
  apihost: "0.0.0.0:8080"
  debughost: "0.0.0.0:4000"
  readtimeout: "10s"
  writetimeout: "10s"
  shutdowntimeout: "10s"
debug: false
db:
  filename: "wasaphoto.db"
  temp: false
