
web:
  apihost: "0.0.0.0:3000"
  debughost: "0.0.0.0:4000"
  readtimeout: "10s"
  writetimeout: "10s"
  shutdowntimeou: "10s"
debug: true
db:
  filename: wasa_photo.db
  persistent: true
  cleanonstart: true